apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ebll
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-service-tenant/appstudio/dc-metro-map-ebll@sha256:cd65434d726f84ad3695dd504122466620fe33f72708889e5f71c6ef5431738a
        name: my-nodejs
        resources: {}
status: {}
